create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid,
  session_id uuid,
  event_type text not null,
  content_type text,
  content_id text,
  content_title text,
  path text,
  referrer text,
  created_at timestamptz not null default now()
);

alter table public.analytics_events enable row level security;

drop policy if exists "Anyone can record analytics events" on public.analytics_events;
create policy "Anyone can record analytics events"
on public.analytics_events for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read analytics events" on public.analytics_events;
create policy "Admins can read analytics events"
on public.analytics_events for select
to authenticated
using (public.is_admin());

create index if not exists analytics_events_created_idx
on public.analytics_events(created_at desc);

create index if not exists analytics_events_type_created_idx
on public.analytics_events(event_type, created_at desc);

create index if not exists analytics_events_content_idx
on public.analytics_events(content_type, content_id, created_at desc);