create table if not exists public.article_topics (
  id bigint generated by default as identity primary key,
  title text not null,
  cover_url text,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.article_topics enable row level security;

drop policy if exists "Public can view published article topics" on public.article_topics;
create policy "Public can view published article topics"
on public.article_topics for select
using (published = true);

drop policy if exists "Admins can manage article topics" on public.article_topics;
create policy "Admins can manage article topics"
on public.article_topics for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

alter table public.articles
  add column if not exists topic_id bigint references public.article_topics(id) on delete set null;

create index if not exists articles_topic_id_idx
on public.articles(topic_id, published_at desc);