create table if not exists public.media_playlists (
  id bigint generated by default as identity primary key,
  title text not null,
  cover_url text,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.media_playlists enable row level security;

drop policy if exists "Public can view published media playlists" on public.media_playlists;
create policy "Public can view published media playlists"
on public.media_playlists for select
using (published = true);

drop policy if exists "Admins can manage media playlists" on public.media_playlists;
create policy "Admins can manage media playlists"
on public.media_playlists for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

alter table public.media
  add column if not exists playlist_id bigint references public.media_playlists(id) on delete set null;

create index if not exists media_playlist_id_idx
on public.media(playlist_id, created_at desc);
