create table if not exists public.quran_classes (
  id bigint generated by default as identity primary key,
  title text not null,
  short_description text,
  description text,
  instructor text,
  timing text,
  age_group text,
  class_type text default 'One-to-One',
  fee numeric,
  registration_url text,
  published boolean not null default false,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.quran_classes enable row level security;

create policy "Public can view published quran classes"
on public.quran_classes for select
using (published = true);

create policy "Admins can manage quran classes"
on public.quran_classes for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create index if not exists quran_classes_published_sort_idx
on public.quran_classes (published, sort_order, created_at desc);