import {useEffect,useState} from 'react'
import {ArrowLeft,BookOpen,GraduationCap,Menu,PlayCircle,X} from 'lucide-react'
import AdminApp from './admin/AdminApp'
import {supabase} from './lib/supabase'
const fallbackMethodology="The Qur'an and the Sunnah upon the understanding of the righteous predecessors (Salaf of the Ummah)."
function App(){
 const[open,setOpen]=useState(false),[courses,setCourses]=useState([]),[articles,setArticles]=useState([]),[media,setMedia]=useState([]),[settings,setSettings]=useState(null),[selectedCourse,setSelectedCourse]=useState(null)
 useEffect(()=>{if(!supabase)return;Promise.all([supabase.from('courses').select('*').eq('published',true).order('created_at',{ascending:false}),supabase.from('articles').select('*').eq('published',true).order('published_at',{ascending:false,nullsFirst:false}),supabase.from('media').select('*').eq('published',true).order('created_at',{ascending:false}),supabase.from('site_settings').select('*').eq('id',1).maybeSingle()]).then(([c,a,m,s])=>{setCourses(c.data||[]);setArticles(a.data||[]);setMedia(m.data||[]);setSettings(s.data)})},[])
 useEffect(()=>{document.body.style.overflow=selectedCourse?'hidden':'';return()=>{document.body.style.overflow=''}},[selectedCourse])
 if(window.location.pathname.startsWith('/admin'))return <AdminApp/>
 const methodology=settings?.methodology||fallbackMethodology
 return <div className="app" dir="rtl">
  <header className="nav"><div className="container nav-inner"><a className="brand" href="#home"><span className="brand-mark">ح</span><span><strong>{settings?.academy_name_urdu||'الحبر اکیڈمی'}</strong><small>{settings?.academy_name||'AL-HIBR ACADEMY'}</small></span></a><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'nav-links open':'nav-links'}>{[['ہوم','#home'],['کورسز','#courses'],['مقالات','#articles'],['میڈیا','#media'],['تعارف','#about']].map(([t,h])=><a key={h} href={h} onClick={()=>setOpen(false)}>{t}</a>)}</nav></div></header>
  <main id="home">
   <section className="hero"><div className="hero-pattern"/><div className="container hero-content"><div className="hero-copy"><span className="eyebrow">الحمد للہ رب العالمین</span><h1>قرآن و سنت کی <span>مستند تعلیم</span></h1><p className="lead">{methodology}</p><p className="hero-text">صحیح اسلامی علم کے ذریعے ایمان کو مضبوط کرنا، عقیدے کی اصلاح اور صالح کردار کی ترغیب دینا۔</p><div className="hero-actions"><a className="btn primary" href="#courses">آن لائن کورسز <ArrowLeft/></a><a className="btn secondary" href="#media"><PlayCircle/> ویڈیوز دیکھیں</a></div></div><div className="hero-card"><div className="seal">ح</div><h2>{settings?.academy_name_urdu||'الحبر اکیڈمی'}</h2><p>Authentic Islamic Knowledge</p><div className="divider"/><p className="arabic">وَقُل رَّبِّ زِدْنِي عِلْمًا</p><small>اور کہیے: اے میرے رب! میرے علم میں اضافہ فرما۔</small></div></div></section>
   <section className="section intro"><div className="container two-col"><div><span className="section-label">ہمارا منہج</span><h2>کتاب و سنت کو سلف صالحین کی سمجھ کے مطابق</h2></div><div><p>{methodology}</p><a className="text-link" href="#about">مزید جانیں <ArrowLeft/></a></div></div></section>
   <section className="section light" id="courses"><div className="container"><div className="section-head"><div><span className="section-label">تعلیم</span><h2>آن لائن کورسز</h2></div></div><div className="cards">{courses.length?courses.map(c=><article className="card course-card" key={c.id} onClick={()=>setSelectedCourse(c)} role="button" tabIndex="0" onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')setSelectedCourse(c)}}>{c.flyer_url&&<img className="content-image course-flyer" src={c.flyer_url} alt={c.title}/>}<div className="card-icon"><GraduationCap/></div><span className="card-tag">آن لائن کورس</span><h3>{c.title}</h3><p className="course-excerpt">{c.short_description||'کورس کی مکمل تفصیلات دیکھنے کے لیے کلک کریں۔'}</p><button className="outline-btn" type="button" onClick={e=>{e.stopPropagation();setSelectedCourse(c)}}>تفصیلات دیکھیں <ArrowLeft/></button></article>):<div className="admin-empty public-empty">نئے کورسز جلد یہاں دستیاب ہوں گے۔</div>}</div></div></section>
   <section className="section" id="articles"><div className="container"><div className="section-head"><div><span className="section-label">علم و تحقیق</span><h2>تازہ مقالات</h2></div></div><div className="article-grid">{articles.length?articles.map(a=><article className="article-card" key={a.id}>{a.cover_url?<img className="content-image article-cover" src={a.cover_url} alt={a.title}/>:<div className="article-placeholder"><BookOpen/></div>}<div className="article-body"><span>{a.category||'اسلامی تعلیم'}</span><h3>{a.title}</h3><p>{a.excerpt||a.content.slice(0,150)}</p></div></article>):<div className="admin-empty public-empty">نئے مقالات جلد یہاں دستیاب ہوں گے۔</div>}</div></div></section>
   <section className="section media" id="media"><div className="container"><div className="section-head"><div><span className="section-label">ویڈیو لائبریری</span><h2>الحبر اکیڈمی یوٹیوب</h2></div><a className="btn primary" href={settings?.youtube_url||'https://youtube.com/@alhibracademyislamic'} target="_blank" rel="noreferrer">یوٹیوب چینل <PlayCircle/></a></div>{media.length>0&&<div className="article-grid">{media.map(v=><article className="article-card" key={v.id}><div className="article-body"><span>{v.type}</span><h3>{v.title}</h3><p>{v.description||''}</p><a className="text-link" href={v.url} target="_blank" rel="noreferrer">ویڈیو دیکھیں <PlayCircle/></a></div></article>)}</div>}</div></section>
   <section className="section about" id="about"><div className="container about-box"><span className="section-label">الحبر اکیڈمی</span><h2>مستند علم، مضبوط ایمان، صالح کردار</h2><p>{methodology}</p></div></section>
  </main>
  {selectedCourse&&<div className="course-modal-backdrop" onClick={()=>setSelectedCourse(null)}><div className="course-modal" onClick={e=>e.stopPropagation()}><button className="course-modal-close" onClick={()=>setSelectedCourse(null)} aria-label="Close"><X/></button>{selectedCourse.flyer_url&&<img className="course-modal-image" src={selectedCourse.flyer_url} alt={selectedCourse.title}/>}<div className="course-modal-body"><span className="card-tag">آن لائن کورس</span><h2>{selectedCourse.title}</h2>{selectedCourse.short_description&&<p className="course-modal-lead">{selectedCourse.short_description}</p>}{selectedCourse.description&&<div><h3>کورس کی تفصیل</h3><p className="course-detail-text">{selectedCourse.description}</p></div>}<div className="course-info-grid">{selectedCourse.instructor&&<div><span>شیخ / استاد</span><strong>{selectedCourse.instructor}</strong></div>}{selectedCourse.duration&&<div><span>دورانیہ</span><strong>{selectedCourse.duration}</strong></div>}{selectedCourse.fee!==null&&selectedCourse.fee!==undefined&&selectedCourse.fee!==''&&<div><span>فیس</span><strong>{selectedCourse.fee}</strong></div>}</div>{selectedCourse.syllabus&&<div className="course-syllabus"><h3>کریکولم / نصاب</h3><p>{selectedCourse.syllabus}</p></div>}{selectedCourse.google_form_url&&<a className="btn primary course-form-btn" href={selectedCourse.google_form_url} target="_blank" rel="noreferrer">کورس میں داخلہ / رجسٹریشن <ArrowLeft/></a>}{settings?.whatsapp_url&&<a className="btn whatsapp-btn" href={settings.whatsapp_url} target="_blank" rel="noreferrer">واٹس ایپ پر رابطہ کریں <ArrowLeft/></a>}{selectedCourse.video_url&&<a className="btn secondary course-video-btn" href={selectedCourse.video_url} target="_blank" rel="noreferrer"><PlayCircle/> کورس ویڈیو دیکھیں</a>}</div></div></div>}
  <footer><div className="container footer-inner"><div><strong>{settings?.academy_name_urdu||'الحبر اکیڈمی'}</strong><p>قرآن و سنت کی مستند تعلیم</p><div className="social-links">{settings?.facebook_url&&<a href={settings.facebook_url} target="_blank" rel="noreferrer" aria-label="Facebook">Facebook</a>}{settings?.instagram_url&&<a href={settings.instagram_url} target="_blank" rel="noreferrer" aria-label="Instagram">Instagram</a>}{settings?.tiktok_url&&<a href={settings.tiktok_url} target="_blank" rel="noreferrer" aria-label="TikTok">TikTok</a>}</div></div><span>© {new Date().getFullYear()} Al-Hibr Academy</span></div></footer>
 </div>
}
export default App
