import{useState}from'react';import{ArrowLeft,BookOpen,GraduationCap,Menu,PlayCircle,X}from'lucide-react';
const methodology="The Qur'an and the Sunnah upon the understanding of the righteous predecessors (Salaf of the Ummah).";
function App(){const[open,setOpen]=useState(false);return <div className="app" dir="rtl">
<header className="nav"><div className="container nav-inner"><a className="brand" href="#home"><span className="brand-mark">ح</span><span><strong>الحبر اکیڈمی</strong><small>AL-HIBR ACADEMY</small></span></a><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'nav-links open':'nav-links'}>{[['ہوم','#home'],['کورسز','#courses'],['مقالات','#articles'],['میڈیا','#media'],['تعارف','#about']].map(([t,h])=><a key={h} href={h} onClick={()=>setOpen(false)}>{t}</a>)}</nav></div></header>
<main id="home"><section className="hero"><div className="hero-pattern"/><div className="container hero-content"><div className="hero-copy"><span className="eyebrow">الحمد للہ رب العالمین</span><h1>قرآن و سنت کی <span>مستند تعلیم</span></h1><p className="lead">{methodology}</p><p className="hero-text">صحیح اسلامی علم کے ذریعے ایمان کو مضبوط کرنا، عقیدے کی اصلاح اور صالح کردار کی ترغیب دینا۔</p><div className="hero-actions"><a className="btn primary" href="#courses">آن لائن کورسز <ArrowLeft/></a><a className="btn secondary" href="#media"><PlayCircle/> ویڈیوز دیکھیں</a></div></div><div className="hero-card"><div className="seal">ح</div><h2>الحبر اکیڈمی</h2><p>Authentic Islamic Knowledge</p><div className="divider"/><p className="arabic">وَقُل رَّبِّ زِدْنِي عِلْمًا</p><small>اور کہیے: اے میرے رب! میرے علم میں اضافہ فرما۔</small></div></div></section>
<section className="section intro"><div className="container two-col"><div><span className="section-label">ہمارا منہج</span><h2>کتاب و سنت کو سلف صالحین کی سمجھ کے مطابق</h2></div><div><p>الحبر اکیڈمی کا مقصد مستند دلائل کی بنیاد پر صحیح اسلامی علم کو عام کرنا، ایمان کو مضبوط کرنا، عقیدے کی اصلاح اور اچھے اخلاق و کردار کی ترغیب دینا ہے۔</p><a className="text-link" href="#about">مزید جانیں <ArrowLeft/></a></div></div></section>
<section className="section light" id="courses"><div className="container"><div className="section-head"><div><span className="section-label">تعلیم</span><h2>آن لائن کورسز</h2></div><a className="text-link" href="#courses">تمام کورسز <ArrowLeft/></a></div><div className="cards">{['قرآن فہمی کا تعارف','عقیدہ اور بنیادی اسلامی علم','سنت اور روزمرہ زندگی'].map(title=><article className="card" key={title}><div className="card-icon"><GraduationCap/></div><span className="card-tag">آن لائن کورس</span><h3>{title}</h3><p>کورس کی مکمل تفصیل، نصاب اور ویڈیو مواد جلد یہاں دستیاب ہوگا۔</p><button className="outline-btn">تفصیل دیکھیں <ArrowLeft/></button></article>)}</div></div></section>
<section className="section" id="articles"><div className="container"><div className="section-head"><div><span className="section-label">علم و تحقیق</span><h2>تازہ مقالات</h2></div><a className="text-link" href="#articles">تمام مقالات <ArrowLeft/></a></div><div className="article-grid">{['علم کی فضیلت اور اس کی اہمیت','قرآن و سنت کی پیروی کیوں ضروری ہے؟','اچھے اخلاق کی اہمیت'].map(title=><article className="article-card" key={title}><div className="article-placeholder"><BookOpen/></div><div className="article-body"><span>اسلامی تعلیم</span><h3>{title}</h3><p>مستند اسلامی مصادر کی روشنی میں علمی تحریر۔</p></div></article>)}</div></div></section>
<section className="section media" id="media"><div className="container media-box"><div><span className="section-label">ویڈیو لائبریری</span><h2>الحبر اکیڈمی یوٹیوب</h2><p>قرآن و سنت کی تعلیمات، دروس اور مفید اسلامی مواد۔</p></div><a className="btn primary" href="https://youtube.com/@alhibracademyislamic" target="_blank" rel="noreferrer">یوٹیوب چینل <PlayCircle/></a></div></section>
<section className="section about" id="about"><div className="container about-box"><span className="section-label">الحبر اکیڈمی</span><h2>مستند علم، مضبوط ایمان، صالح کردار</h2><p>{methodology}</p></div></section></main>
<footer><div className="container footer-inner"><div><strong>الحبر اکیڈمی</strong><p>قرآن و سنت کی مستند تعلیم</p></div><span>© {new Date().getFullYear()} Al-Hibr Academy</span></div></footer></div>}export default App;